### ISSUE TITLE
Solution doesn't build in VS 2019

### ISSUE THREAD

**Issue by tiesmaster** [justcla/HotCommands#83]
As discussed in #81, and #82, the build is failing, and needs to be fixed before #82 can be merged.

When opening up `HotCommands.sln` in VS 2019, I now get

```
Commands\ToggleComment.cs(13,30): error CS0234: The type or namespace name 'Language' does not exist in the namespace 'Microsoft.VisualStudio' (are you missing an assembly reference?) [C:\src\oss\HotCommands\HotCommands\HotCommands.csproj]
```

I've tracked that down to missing nuget reference in `packages.config`, commit 34cf0de fixes that, but results in another build error:
```
The "ValidateVsixManifest" task failed unexpectedly.
System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2, String path3)
   at Microsoft.VisualStudio.Sdk.BuildTasks.ValidateVsixManifestUtilitiesLegacy.ValidateVsix(TaskLoggingHelper log, String manifestToValidate, String vsixSchemaPath, Boolean validateEverything, String& name, String& id)
   at Microsoft.VisualStudio.Sdk.BuildTasks.ValidateVsixManifest.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

Don't really understand what's going on there, so I need to dig into that.

**Comment by tiesmaster** [comment]
Alright, figured it out: "non-existing error". I cleared out the `obj` directory, and it built. It was caused by a stale build cache containing some `....npkg.props` file that referenced the `Microsoft.VisualStudio.Sdk.BuildTasks` package, giving the above error.

@justcla Please try PR #84 to see if it fixes the build for you. I'll drop the draft status, so you merge it, if you want.

**Comment by justcla** [comment]
Thanks. I'll give it a go.

**Comment by justcla** [comment]
It builds now. All fixed.
